[feat/#2] 1주차 과제 구현
AND-SOPT-ANDROID/yein-kang pull request #4
Opened 2024-10-10 06:37 UTC by kangyein9892

## Related issue 🛠
- closed #2 

## Work Description ✏️
- 회원가입 화면
- 로그인 화면
- 마이페이지 화면
- 텍스트 입력 시 2줄 방지, 엔터 클릭 시 다음 입력칸으로 넘어가도록 구현

## Screenshot 📸
- 회원가입

https://github.com/user-attachments/assets/4bc20967-e169-48de-a0c6-ede66b9d1c5d

- 로그인

https://github.com/user-attachments/assets/2aa96ccf-b124-4ef4-b183-3a4bcebe354e

## Uncompleted Tasks 😅
- 심화과제
  - [ ] Viewmodel 활용하기
  - [ ] 자동 로그인 구현 (SharedPreference 활용, 로그아웃)
  - [ ] 스택 관리
  - [ ] 클릭 시 리플효과
  - [ ] 키보드가 올라올 때 버튼을 가리지 않도록 구현

## To Reviewers 📢
- 코리 받고 고칠 거 있으면 반영 받고 심화 과제 해보려고요 ...!! 해보다가 들었던 생각이 그냥 viewmodel 쓰는게 편했겠다는 생각도 들었고, 자동로그인도 그냥 같이 구현할 걸 그랬어요...!! ㅠㅠ (괜히 귀찮아진 것 같네요...)
- mvi 살짝 봐서 공부했을때 state(model), intent 했던거 해서 했는데 맞는지는 전혀 모르겠네요 하하....
- 컴포넌트 분리해보는게 처음이라 재사용되는 것 같은 애들만 분리해봤는데 맞는지는 모르겠습니다....~
- 어쨌든 일단 끝입니다...! ㅠㅠ

2024-10-10 07:30 UTC, boiledEgg-s requested changes
진짜 너무 잘한다👍
조장 자리가 위태위태하네요,,

2024-10-10 07:30 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +        finish()
그냥 `finish()` 함수를 호출하는 것보단 심화 과제 중에 `IntentFlag`를 사용해서 스택관리를 하는게 있었는데 적용해보면 좋을 것 같아요!

2024-10-10 07:30 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +    navigationIconContentColor: Color = Color.White
```suggestion
fun BackTopBar(
    @DrawableRes titleImg:  Int,
    onBtnClick: () -> Unit,
    modifier: Modifier = Modifier
    containerColor: Color = FirstGrey,
    titleContentColor: Color = Color.White,
    navigationIconContentColor: Color = Color.White
```
컴포넌트라는게 여러 컴포저블에서 호출될 수 있는거니까 기본적으로 Modifier를 인자로 받는게 좋습니다!

저는 보통 최상위 컴포저블에 인자로 받은 Modifier를 할당해서 사용하는 편입니다!

또한 Modifier는 기본값이 있는 선택 인자로 받는 편이고, 함수 인자의 순서는 "필수 인자 -> Modifier -> 선택 인자" 순으로 적으시면 됩니다!

2024-10-10 07:30 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +                contentDescription = null,
`contentDescription`이 좀 귀찮을 수 있지만, 용도가 있는 것이니 써주면 좋을 것 같아요!
[용도가 궁금하다면? 클릭](https://studyforcoding.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-ImageView%EC%97%90%EC%84%9C-contentDescription%EC%9D%98-%EC%97%AD%ED%95%A0)

2024-10-10 07:30 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +    onBtnClick: () -> Unit,
네이밍은 길어져도 좋으니까 명확하게 `onButtonClick()`으로 써주는걸 추천합니다!

2024-10-10 07:30 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +}
나중에 협업하다 보면 컴포넌트를 같이 쓰는 경우가 빈번하게 발생할텐데, 다른 팀원의 코드를 이해할 때 Preview 만한게 없더라구요!
귀찮겠지만 컴포넌트는 Preview를 작성하는걸 습관하면 좋습니다!!

2024-10-10 07:30 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/component/ContentsView.kt
> +    modifier: Modifier
```suggestion
    modifier: Modifier = Modifier
```
수정자는 일반적으로 기본값을 설정해서 사용합니다!

2024-10-10 07:30 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/component/OtherServiceIconRow.kt
> +                .background(Color(0xFFFFEC00))
색상, 문자열 등은 하드코딩을 지양합시다!!

2024-10-10 07:30 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/component/WavveActionTextField.kt
> +    var showPassword by remember { mutableStateOf(false) }
다른 변수들과는 다르게 이 변수는 왜 인자로 받지 않고 여기서 선언하신건가요??

2024-10-10 07:30 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/my/MyActivity.kt
> +                    }
컴포즈 처음 하는거 맞냐고.. 😮

2024-10-10 07:30 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/signin/SignInActivity.kt
> +    }
그저 WOW네요,, 처음 보는 이벤트 처리 방식이네요
이벤트를 처리하기 위한 Intent 클래스를 만들고 when문으로 상황별 처리를 해준 것으로 보이네요ㄷㄷ

최근에 알게 된 이벤트 처리 방법이 있는데, `Channel`객체를 사용해서 구현하신 방법과 비슷한데 좀 더 컴포즈스럽더라구요! 저도 잘은 몰라서 설명은 못하지만 Channel과 Flow에 관해서 찾아보시면 아주 좋을 것 같습니당!! (근데 이게 1주차 리뷰가 맞나..? 왤케 잘하는데,,,)

2024-10-10 07:30 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/signin/SignInScreen.kt
> +    modifier: Modifier
상태 호이스팅 감동적이네요,,ㅠ

2024-10-10 07:30 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/signin/SignInScreen.kt
> +            },
인자가 없는 경우, 혹은 함수의 인자 순서와 람다의 변수 순서가 같다면 람다 없이 함수이름만 적으셔도 됩니다!
가독성이 더 좋아지겠죠?
```suggestion
            onClick = onSignInButtonClick,
```

2024-10-10 07:30 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/signin/intent/SignInIntent.kt
확실히 플러터 짬바가 들어나네요!

2024-10-10 11:14 UTC, unam98 reviewed
안녕하세요 명예 ob 리뷰어로 참여하게된 김우남이라고 합니다~! 👍🏻

2024-10-10 11:14 UTC, unam98 commented on app/src/main/java/org/sopt/and/signin/SignInActivity.kt
> +            val snackBarMessage = data?.getStringExtra("snackBarMessage") ?: ""
getExtra에 넣는 key값은 상수로 빼서 사용하시면 휴먼 에러를 방지할 수 있고 더 사용하기 편할 것 같습니다 :)

2024-10-10 11:14 UTC, unam98 commented on app/src/main/java/org/sopt/and/signin/model/SignInState.kt
> +    val signInSuccessful: Boolean = false,
보통 Boolean 타입 변수 이름은 is라는 접두어를 붙여서 많이 사용하는 것 같아요! 
ex) isSignInSuccess

2024-10-10 11:14 UTC, unam98 commented on app/src/main/java/org/sopt/and/signup/SignUpActivity.kt
> +                        intent.putExtra("snackBarMessage", getString(R.string.signup_success_text))
```
intent.apply {
    putExtra("id", currentState.id)
    putExtra("password", currentState.password)
    putExtra("snackBarMessage", getString(R.string.signup_success_text))
}
```

요런식으로 scope function 활용해서 더 가독성 좋게 사용할 수 있을 것 같아요!

2024-10-11 06:24 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/signin/SignInActivity.kt
> +    private fun handledIntent(state: MutableState<SignInState>, intent: SignInIntent) {
이벤트 처리 방식 새롭게 알아갑니다!!

2024-10-11 06:29 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/ui/theme/Color.kt
> +val FirstGrey = Color(0xFF1B1B1B)
컬러를 미리 정의해서 쓰기 편할 것 같아요!! 굿굿!!

2024-10-11 06:30 UTC, serioushyeon approved these changes

2024-10-11 08:56 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +    navigationIconContentColor: Color = Color.White
그렇게 생각을 못했네요,,,! 컴포저블이 여러 컴포저블에서 호출하는거니까 인자로 받는게 좋겟네요 ㅎㅎ
함수 인자 순서도 생각하면서 해보겠습니다!

2024-10-11 08:56 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +                contentDescription = null,
이건 제가 수정하려고 했는데 까먹고 놓쳤네요... 감사합니다!

2024-10-11 08:56 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +}
Preview의 목적이 단순히 나만 미리보려고 생각했는데 협업할때는 중요하겠네요 !! 생각하지 못했던 부분인데 감사합니다 ~

2024-10-11 08:57 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/component/WavveActionTextField.kt
> +    var showPassword by remember { mutableStateOf(false) }
아마 제가 처음에 할때 고쳐야지 하고 놓친 것 같네요... 이건 제가 수정하겠습니다 !!

2024-10-11 08:57 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/my/MyActivity.kt
> +                    }
맞아요... 😅 힘들다 휴우

2024-10-11 08:58 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/signin/SignInActivity.kt
> +    }
저도 flow와 channel 들어본 적은 있는데 여기서 적용하면 괜찮겠군요 ! 나중에 같이 공부하면서 적용해보는걸로 ~~

2024-10-11 08:58 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/signin/SignInScreen.kt
> +            },
알고 있던 사실인데도 놓쳤네요 ㅎㅎ 감사합니다

2024-10-11 08:59 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/signin/intent/SignInIntent.kt
칭찬 감사합니다... 민망하네요 많이 부족합니다 ^^

2024-10-11 08:59 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/signin/SignInActivity.kt
> +            val snackBarMessage = data?.getStringExtra("snackBarMessage") ?: ""
상수로 빼는 습관을 들여야겠네요! 감사합니다!

2024-10-11 08:59 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/signin/model/SignInState.kt
> +    val signInSuccessful: Boolean = false,
앞으로는 그렇게 진행해볼게요 !!

2024-10-11 09:00 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/signup/SignUpActivity.kt
> +                        intent.putExtra("snackBarMessage", getString(R.string.signup_success_text))
scope function을 알고있었지만 여기서 또 활용해야겠다는 생각을 못했네요 감사합니다 😊

2024-10-11 09:00 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/ui/theme/Color.kt
> +val FirstGrey = Color(0xFF1B1B1B)
감사합니다 ~~

2024-10-11 09:24 UTC, jm991014 approved these changes
MVI 관련해서 따로 구현해본 적이 없어서 피드백을 드릴 수는 없지만.. 칭찬은 드릴 수 있습니다. 너무 잘하시네요 ㅋㅎ👍 많이 배워갑니다~~

2024-10-11 09:24 UTC, jm991014 commented on app/src/main/java/org/sopt/and/signup/SignUpScreen.kt
> +            },
이런 방식으로 사용할 수도 있군요.. 배워갑니다~

2024-10-11 09:24 UTC, jm991014 commented on app/src/main/java/org/sopt/and/my/MyScreen.kt
> +        )
요거 HorizontalDivider()라고 함수가 있는데, 똑같은 기능이라 한 번 참고해보시면 좋을 것 같아요ㅎㅎ

2024-10-11 09:24 UTC, jm991014 commented on app/src/main/java/org/sopt/and/component/PairTextView.kt
> +
컴포넌트 분리를 걱정하신 것에 비해 너무 깔끔하게 잘 하셨네요 멋져요~

2024-10-11 09:24 UTC, jm991014 commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +                painter = painterResource(id = titleImg),
[여기](https://github.com/AND-SOPT-ANDROID/minseok-shin/pull/2#discussion_r1793129676)한 번 읽어보시면 좋을 것 같아요!! 저도 처음 알아가지고.. 공유해봅니다..ㅎㅎ

2024-10-11 10:24 UTC, unam98 commented on app/src/main/java/org/sopt/and/signin/model/SignInState.kt
> +    val signInSuccessful: Boolean = false,
클린코드라는 책에서 변수 네이밍에 대한 내용을 다루는데 실무에서 보편적으로 쓰이는 것 같아서 시간 되시면 나중에 참고 차 한 번 읽어보시는 것도 추천드립니다 :)

2024-10-11 10:24 UTC, unam98 commented on app/src/main/java/org/sopt/and/signin/model/SignInState.kt
> +    val signInSuccessful: Boolean = false,
클린코드라는 책에서 변수 네이밍에 대한 내용을 다루는데 실무에서 보편적으로 쓰이는 것 같아서 시간 되시면 나중에 참고 차 한 번 읽어보시는 것도 추천드립니다 :)

2024-10-11 11:01 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/my/MyScreen.kt
> +        )
오 감사합니다 !! 다음에 한번 적용해볼게요 ~~

2024-10-11 11:01 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/component/PairTextView.kt
> +
과찬이십니다 감사합니다...

2024-10-11 11:02 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/component/BackTopBar.kt
> +                painter = painterResource(id = titleImg),
와 덕분에 완전 좋은 거 알아가네요 !! 대박 감사합니다 ~~

2024-10-11 11:03 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/signin/model/SignInState.kt
> +    val signInSuccessful: Boolean = false,
좋은 책 추천해주셔서 감사합니다 😊 다음에 꼭 읽어볼게요 ~~

2024-10-11 11:12 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +        finish()
이건... 심화과제 할때 해보겠습니다...

2024-10-11 11:20 UTC, unam98 commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +        finish()
안드로이드 스택 관리 관련하여 launchMode라는 개념이 있습니다. 이 부분 공부해보시는 걸 추천드립니다!

2024-10-14 00:43 UTC, boiledEgg-s approved these changes
너무 잘하시네요,, 수정하느라 고생많으셨어요!!
2주차도 화이팅하시당

2024-10-16 09:34 UTC, jihyunniiii reviewed
고생하셨습니다 ~

2024-10-16 09:34 UTC, jihyunniiii commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Theme.ANDANDROID" />
지금 application에서 theme를 설정해주고 있죠?
이렇게 설정하면 해당 theme이 기본 theme가 됩니다.
즉, 공통적인 theme을 사용한다면, activity에 theme를 중복으로 설정해주지 않아도 됩니다.

2024-10-16 09:34 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/signin/SignInActivity.kt
> +            val snackBarMessage = data?.getStringExtra(SNACK_BAR_MESSAGE) ?: DEFAULT_STRING
꼼꼼하게 상수화 잘 해주셨네요

2024-10-16 09:34 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/signup/SignUpActivity.kt
> +    }
Regex 객체 생성은 CPU를 많이 요구하는 작업 중 하나입니다.
이렇게 로직을 작성하게 되면 해당 함수를 실행할 때마다 객체를 생성하게 되어 성능이 저하될 수 있겠죠?
싱글톤 패턴을 사용하시는 것이 좋을 것 같네요.

2024-10-25 03:15 UTC, merged